### PR TITLE
Update gradle and dependencies

### PR DESCRIPTION
**Pull request by apoi**

### CODE REVIEW

**Comment by tomaszpolanski** [comment]
@apoi Licenses for the new build tools are not accepted

**Comment by apoi** [comment]
Looks like that was fixed a couple of days ago in https://github.com/travis-ci/travis-ci/issues/8874. Some other failures left though

**Comment by apoi** [comment]
Powermock 1.7 wasn't compatible with 1.6, downgraded that.

**Comment by omjokine** [comment]
How about bumping version number and releasing a new version since rxjava2 and stuff is there? :)

**Comment by apoi** [comment]
@omjokine, yes a new version should be created. However currently only @tehmou can trigger that, perhaps I'll look into JitPack to make releasing a bit easier

**Pull request merged**
