### PR TITLE
update config travils

### PR DESCRIPTION
**Pull request by ulx**

### CODE REVIEW

**Comment by jaggernod** [comment]
Is there any benefit for not failing on lint errors?

**Comment by ulx** [comment]
assembly application after commit

**Comment by jaggernod** [comment]
Won't it lead to people not paying attention to the lint errors, as it "would still build"?

**Comment by ulx** [comment]
@jaggernod Ok. How do better?

**Comment by jaggernod** [comment]
Just asking if we really need/want `abortOnError false`? If this option won't accually introduce ability to grow debt as people will ignore lint reports.

**Comment by ulx** [comment]
Now I do not know any other way to build

**Pull request closed without merging**
